### ISSUE TITLE
Updater action fails: `org.microg.nlp.backend.ichnaea` no longer exists

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/android_vendor_partner_gms#35]
See https://github.com/lineageos4microg/android_vendor_partner_gms/actions/runs/11144988693
```
Run pipenv run python main.py
  pipenv run python main.py
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
    pythonLocation: /opt/hostedtoolcache/Python/3.9.20/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.20/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.20/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.20/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.20/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.20/x64/lib
Traceback (most recent call last):
FakeStore up to date.
FDroid up to date.
  File "/home/runner/work/android_vendor_partner_gms/android_vendor_partner_gms/updater/main.py", line 47, in <module>
    update_if_needed('IchnaeaNlpBackend', fdroid_recommended_release(fdroid_main_repo, 'org.microg.nlp.backend.ichnaea'))
  File "/home/runner/work/android_vendor_partner_gms/android_vendor_partner_gms/updater/sources.py", line 38, in fdroid_recommended_release
    raise Exception('Did not find {} in repo {}'.format(application_id, repo))
Exception: Did not find org.microg.nlp.backend.ichnaea in repo https://www.f-droid.org/repo
FDroidPrivilegedExtension ahead of suggested version (2130 > 2070)
GmsCore up to date.
GsfProxy up to date.
Error: Process completed with exit code 1.
```

**Comment by petefoth** [comment]
Fixed in [commit 356b5d8](https://github.com/lineageos4microg/android_vendor_partner_gms/commit/356b5d8ebe259231f29424409ecd674d00fd4a6d)

- See [this run](https://github.com/lineageos4microg/android_vendor_partner_gms/actions/runs/11534620620)
